const beatlesEvents = [
    // === Pre-Beatles (1956–1960) ===
    { event: "John Lennon forms The Quarrymen", year: 1956, description: "John forms his first skiffle group." },
    { event: "Paul McCartney meets John Lennon", year: 1957, description: "Meeting at the Woolton Parish Church Garden Fete." },
    { event: "Paul joins The Quarrymen", year: 1957, description: "Paul officially joins John's group." },
    { event: "George Harrison joins The Quarrymen", year: 1958, description: "George joins at Paul's recommendation." },
    { event: "The Quarrymen record 'That'll Be the Day'", year: 1958, description: "Their first amateur recording." },
    { event: "John Lennon's mother Julia dies", year: 1958, description: "A tragic loss that influenced John's music." },
    { event: "Ringo Starr joins Rory Storm and the Hurricanes", year: 1959, description: "Ringo's early band." },
    { event: "The Beatles name is chosen", year: 1960, description: "Official transition to the 'Beatles' name." },
    { event: "Stuart Sutcliffe joins The Beatles", year: 1960, description: "Art school friend becomes bassist." },
    { event: "First Hamburg residency begins", year: 1960, description: "Performing at the Indra Club." },
    { event: "George Harrison deported from Germany", year: 1960, description: "Deported for being underage." },
    { event: "Pete Best joins The Beatles as drummer", year: 1960, description: "Recruited for Hamburg trip." },

    // === Rise to fame (1961–1963) ===
    { event: "First gig at The Cavern Club", year: 1961, description: "Start of their legendary residency." },
    { event: "Brian Epstein first sees The Beatles", year: 1961, description: "At The Cavern Club in Liverpool." },
    { event: "Tony Sheridan sessions in Hamburg", year: 1961, description: "Recording 'My Bonnie' as backing band." },
    { event: "Stuart Sutcliffe leaves The Beatles", year: 1961, description: "Stays in Hamburg to pursue art." },
    { event: "The Beatles sign with Brian Epstein", year: 1962, description: "Brian officially becomes their manager." },
    { event: "Decca Records audition and rejection", year: 1962, description: "Turned down by Dick Rowe." },
    { event: "Stuart Sutcliffe dies", year: 1962, description: "Original bassist passes away in Hamburg." },
    { event: "Recording contract with Parlophone", year: 1962, description: "Signed by George Martin." },
    { event: "Ringo Starr joins The Beatles", year: 1962, description: "Replacing Pete Best on drums." },
    { event: "Release of 'Love Me Do'", year: 1962, description: "Their debut single." },
    { event: "John Lennon marries Cynthia Powell", year: 1962, description: "Private ceremony in Liverpool." },
    { event: "The Beatles' first recording at Abbey Road", year: 1962, description: "June 6, 1962 audition session." },
    { event: "The Beatles' first appearance on UK TV", year: 1962, description: "On 'People and Places'." },
    { event: "First concert at The Star-Club Hamburg", year: 1962, description: "Hamburg residency." },
    { event: "Beatles first radio interview", year: 1962, description: "Radio Clatterbridge." },
    { event: "Release of 'Please Please Me' single", year: 1963, description: "Their first #1 hit." },
    { event: "Release of 'Please Please Me' album", year: 1963, description: "Debut LP recorded in one day." },
    { event: "John's son Julian Lennon born", year: 1963, description: "John's first child." },
    { event: "Release of 'From Me to You' single", year: 1963, description: "Third single, #1 hit." },
    { event: "Release of 'She Loves You' single", year: 1963, description: "Best-selling single in UK history at the time." },
    { event: "Beatlemania begins (Palladium performance)", year: 1963, description: "Headline show on 'Sunday Night at the London Palladium'." },
    { event: "Release of 'With The Beatles'", year: 1963, description: "Their second album." },
    { event: "Release of 'I Want to Hold Your Hand'", year: 1963, description: "Single that broke America." },
    { event: "The Beatles' Royal Variety Performance", year: 1963, description: "John's 'rattle your jewellery' quip." },
    { event: "First Christmas record for fan club", year: 1963, description: "Annual tradition begins." },

    // === Conquering America & World Tours (1964) ===
    { event: "The Beatles arrive in USA", year: 1964, description: "Landed at JFK airport to mass hysteria." },
    { event: "First Ed Sullivan Show appearance", year: 1964, description: "73 million people watched." },
    { event: "The Beatles hold top 5 positions on Billboard Hot 100", year: 1964, description: "Unprecedented chart domination." },
    { event: "Release of 'A Hard Day's Night' film", year: 1964, description: "Directed by Richard Lester." },
    { event: "Release of 'A Hard Day's Night' album", year: 1964, description: "First album of all original songs." },
    { event: "Meeting Bob Dylan", year: 1964, description: "Crucial meeting in New York's Hotel Delmonico." },
    { event: "Meeting with Muhammad Ali", year: 1964, description: "Photo op during Miami tour." },
    { event: "Release of 'Beatles for Sale'", year: 1964, description: "UK release, fourth album." },
    { event: "First world tour begins", year: 1964, description: "Visiting Denmark, Netherlands, Hong Kong, Australia." },

    // === Peak years (1965) ===
    { event: "Release of 'Help!' single", year: 1965, description: "John's cry for help." },
    { event: "Ringo marries Maureen Cox", year: 1965, description: "Official wedding." },
    { event: "The Beatles movie 'Help!' premieres", year: 1965, description: "Royal premiere in London." },
    { event: "Release of 'Help!' album", year: 1965, description: "Transitional album." },
    { event: "Shea Stadium concert", year: 1965, description: "Record-breaking crowd of 55,600." },
    { event: "The Beatles meet Elvis Presley", year: 1965, description: "At Elvis's home in Bel Air." },
    { event: "Awarded MBEs", year: 1965, description: "Member of the Order of the British Empire." },
    { event: "Release of 'Rubber Soul'", year: 1965, description: "Studio evolution; folk-rock masterpiece." },
    { event: "Release of 'Day Tripper' / 'We Can Work It Out'", year: 1965, description: "Double A-side single." },
    { event: "Release of single 'Ticket to Ride'", year: 1965, description: "One of the heaviest singles of its era." },

    // === Studio revolution (1966) ===
    { event: "George Harrison marries Pattie Boyd", year: 1966, description: "Married after meeting on the set of AHDN." },
    { event: "John's 'More popular than Jesus' quote", year: 1966, description: "Controversial interview in the Evening Standard." },
    { event: "Beatles record burning protests in the US", year: 1966, description: "Backlash to John's Jesus comment." },
    { event: "Release of 'Revolver'", year: 1966, description: "Groundbreaking studio work with tape loops." },
    { event: "Release of 'Paperback Writer' single", year: 1966, description: "Innovative A-side." },
    { event: "Final official concert at Candlestick Park", year: 1966, description: "End of their touring years." },
    { event: "John Lennon meets Yoko Ono", year: 1966, description: "At Indica Gallery in London." },
    { event: "The Beatles' first Japan tour", year: 1966, description: "Performing at the Budokan." },
    { event: "The Beatles' Manila tour controversy", year: 1966, description: "Snubbing Imelda Marcos leads to chaos." },
    { event: "Meeting of The Beatles and The Beach Boys", year: 1966, description: "Mutual influence peak, Pet Sounds era." },
    { event: "Recording 'Strawberry Fields Forever'", year: 1966, description: "Start of Sgt. Pepper sessions." },

    // === Psychedelic era (1967) ===
    { event: "Release of 'Strawberry Fields' / 'Penny Lane'", year: 1967, description: "Double A-side masterpiece." },
    { event: "Release of 'Sgt. Pepper's Lonely Hearts Club Band'", year: 1967, description: "Masterpiece release." },
    { event: "The Beatles play on 'Our World' broadcast", year: 1967, description: "Performing 'All You Need Is Love' to 400 million." },
    { event: "Release of 'All You Need Is Love' single", year: 1967, description: "Global anthem." },
    { event: "The Beatles meet Maharishi Mahesh Yogi", year: 1967, description: "Start of their spiritual era." },
    { event: "Death of Brian Epstein", year: 1967, description: "Manager dies at 32." },
    { event: "Magical Mystery Tour telecast", year: 1967, description: "Airing on Boxing Day, panned by critics." },
    { event: "Release of 'A Day in the Life'", year: 1967, description: "Final track on Sgt. Pepper." },
    { event: "Apple Boutique opens on Baker Street", year: 1967, description: "Short-lived retail venture." },

    // === Turbulent year (1968) ===
    { event: "Beatles travel to India (Rishikesh)", year: 1968, description: "Studying TM with Maharishi." },
    { event: "Apple Corps is formed", year: 1968, description: "Business venture launch." },
    { event: "Release of 'Lady Madonna' single", year: 1968, description: "Return to rock & roll roots." },
    { event: "Release of 'Hey Jude'", year: 1968, description: "Biggest-selling single of their career." },
    { event: "Release of 'Yellow Submarine' film", year: 1968, description: "Animated psychedelic classic." },
    { event: "Recording of the 'White Album' begins", year: 1968, description: "Tense sessions begin at Abbey Road." },
    { event: "Ringo Starr briefly leaves the band", year: 1968, description: "Walked out during White Album sessions." },
    { event: "Yoko Ono joins the studio sessions", year: 1968, description: "During White Album recording." },
    { event: "Release of 'The Beatles' (White Album)", year: 1968, description: "Double album release." },
    { event: "John and Yoko's 'Two Virgins' album released", year: 1968, description: "Controversial nude cover." },
    { event: "Apple Boutique closes; stock given away free", year: 1968, description: "End of retail experiment." },

    // === The end (1969–1970) ===
    { event: "Get Back / Let It Be sessions begin", year: 1969, description: "Filmed at Twickenham Studios." },
    { event: "George Harrison temporarily quits the band", year: 1969, description: "Walks out during Let It Be sessions." },
    { event: "Rooftop Concert", year: 1969, description: "Final public performance atop Apple Corps." },
    { event: "John Lennon marries Yoko Ono", year: 1969, description: "Wedding in Gibraltar." },
    { event: "John and Yoko's Bed-In for Peace", year: 1969, description: "Amsterdam Hilton protest." },
    { event: "Paul McCartney marries Linda Eastman", year: 1969, description: "Wedding at Marylebone Registry Office." },
    { event: "Release of 'The Ballad of John and Yoko'", year: 1969, description: "Recorded by just John and Paul." },
    { event: "Release of 'Something' / 'Come Together'", year: 1969, description: "George's first A-side single." },
    { event: "Release of 'Abbey Road'", year: 1969, description: "Last recorded album." },
    { event: "The 'Paul is Dead' rumor spreads", year: 1969, description: "Urban legend peak." },
    { event: "John Lennon quietly leaves the band", year: 1969, description: "Informs group he wants 'divorce'." },
    { event: "John's debut single 'Give Peace a Chance'", year: 1969, description: "Peace anthem with Plastic Ono Band." },
    { event: "John Lennon launches Plastic Ono Band", year: 1969, description: "New artistic direction." },
    { event: "John Lennon returns his MBE", year: 1969, description: "Protesting Vietnam war and Biafra." },
    { event: "Paul announces official breakup", year: 1970, description: "Public statement in April 1970." },
    { event: "Release of 'Let It Be' album", year: 1970, description: "Final studio release, produced by Phil Spector." },
    { event: "Let It Be film premieres", year: 1970, description: "Documentary release." },
    { event: "Release of 'Instant Karma!'", year: 1970, description: "John's hit single produced by Spector." },
    { event: "Paul McCartney's debut solo album 'McCartney'", year: 1970, description: "Lo-fi home-recorded masterpiece." },
    { event: "George releases 'All Things Must Pass'", year: 1970, description: "Critically acclaimed triple solo debut." },

    // === Solo years & legacy (1971–2024) ===
    { event: "Concert for Bangladesh", year: 1971, description: "Organized by George Harrison at Madison Square Garden." },
    { event: "John Lennon releases 'Imagine'", year: 1971, description: "Legendary solo album." },
    { event: "Wings is formed by Paul McCartney", year: 1971, description: "Paul's new band with Linda." },
    { event: "Ringo releases 'It Don't Come Easy'", year: 1971, description: "First solo hit single." },
    { event: "George Harrison sued over 'My Sweet Lord'", year: 1971, description: "Plagiarism lawsuit begins." },
    { event: "John and Yoko move to New York City", year: 1971, description: "Settling in The Dakota." },
    { event: "John Lennon's 'Happy Xmas (War is Over)'", year: 1971, description: "Christmas protest anthem." },
    { event: "Paul & Wings release 'Band on the Run'", year: 1973, description: "Critically acclaimed album." },
    { event: "John Lennon's Lost Weekend begins", year: 1973, description: "18-month separation from Yoko." },
    { event: "John Lennon's deportation battle", year: 1973, description: "US government tries to deport Lennon." },
    { event: "George Harrison's Dark Horse tour", year: 1974, description: "First solo US tour." },
    { event: "The Beatles officially legally dissolve", year: 1975, description: "End of the legal entity." },
    { event: "John Lennon's son Sean Lennon born", year: 1975, description: "John becomes a stay-at-home dad." },
    { event: "John Lennon wins green card", year: 1976, description: "Allowed to stay in the USA." },
    { event: "Wings release 'Mull of Kintyre'", year: 1977, description: "Best-selling UK single of the decade." },
    { event: "Release of 'Double Fantasy'", year: 1980, description: "John and Yoko's comeback album." },
    { event: "Death of John Lennon", year: 1980, description: "Assassinated outside The Dakota in New York." },
    { event: "Concert for George at Royal Albert Hall", year: 2002, description: "Tribute to George Harrison." },
    { event: "The Beatles inducted into Rock Hall of Fame", year: 1988, description: "Posthumous honor for the group." },
    { event: "Anthology documentary series premieres", year: 1995, description: "Comprehensive history project." },
    { event: "Release of 'Free as a Bird' single", year: 1995, description: "New Beatles single from Lennon demo." },
    { event: "Release of 'Real Love' single", year: 1996, description: "Second 'new' Beatles single." },
    { event: "Paul McCartney receives Knighthood", year: 1997, description: "Sir James Paul McCartney." },
    { event: "Linda McCartney dies", year: 1998, description: "Paul's first wife passes away." },
    { event: "George Harrison stabbed by intruder", year: 1999, description: "Home invasion at Friar Park." },
    { event: "The Beatles' 1 compilation hits #1 worldwide", year: 2000, description: "Best-selling compilation album ever." },
    { event: "George Harrison dies", year: 2001, description: "Passes away in Los Angeles from cancer." },
    { event: "Beatles catalog arrives on iTunes", year: 2010, description: "Digital milestone after years of holdout." },
    { event: "Beatles catalog arrives on streaming", year: 2015, description: "Available on Spotify, Apple Music." },
    { event: "George Martin dies", year: 2016, description: "The 'Fifth Beatle' passes away at 90." },
    { event: "Ringo Starr receives Knighthood", year: 2018, description: "Sir Richard Starkey." },
    { event: "Release of 'Get Back' documentary", year: 2021, description: "Peter Jackson's restoration of Let It Be sessions." },
    { event: "The Beatles' 'Now and Then' release", year: 2023, description: "Final song finished with AI technology." },
    { event: "Paul McCartney plays Giza pyramids", year: 2024, description: "Historic concert continuing the legacy." },

    // === Additional deep-cut events ===
    { event: "John Lennon starts writing 'In My Life'", year: 1965, description: "One of his most personal songs." },
    { event: "George Harrison discovers the sitar", year: 1965, description: "Influenced by Ravi Shankar." },
    { event: "The Beatles' Butcher Cover photo shoot", year: 1966, description: "Controversial 'Yesterday and Today' cover." },
    { event: "Recording of 'Tomorrow Never Knows'", year: 1966, description: "Revolutionary tape-loop techniques." },
    { event: "Paul McCartney composes 'Yesterday'", year: 1965, description: "Dreamed the melody, initially called 'Scrambled Eggs'." },
    { event: "George Harrison visits Haight-Ashbury", year: 1967, description: "Disillusioned by the hippie scene." },
    { event: "Recording of 'A Day in the Life'", year: 1967, description: "Orchestra session for the climactic crescendo." },
    { event: "John writes 'I Am the Walrus'", year: 1967, description: "Inspired by Lewis Carroll." },
    { event: "George Harrison arrested for marijuana", year: 1969, description: "Busted on his wedding anniversary." },
    { event: "Allen Klein becomes manager", year: 1969, description: "Divisive appointment opposed by Paul." },
    { event: "Paul sues to dissolve The Beatles partnership", year: 1970, description: "Legal action on Dec 31." },
    { event: "John Lennon's Primal Therapy", year: 1970, description: "Sessions with Arthur Janov." },
    { event: "Ringo Starr releases 'Photograph'", year: 1973, description: "Co-written with George Harrison." },
    { event: "Paul McCartney arrested for marijuana in Japan", year: 1980, description: "Spent 10 days in jail." },
    { event: "Live Aid — Paul McCartney performs", year: 1985, description: "Mic failure during 'Let It Be'." },
    { event: "Beatles songs used in 'Across the Universe' film", year: 2007, description: "Musical film based on their catalog." },
    { event: "Cirque du Soleil 'LOVE' premieres", year: 2006, description: "Beatles-themed show in Las Vegas." },
    { event: "Paul McCartney performs at Glastonbury", year: 2022, description: "Oldest solo headliner at 80." },
    { event: "EMI releases remastered Beatles catalog", year: 2009, description: "Stereo and mono remasters." },
    { event: "Ringo's All-Starr Band first tour", year: 1989, description: "Beginning of Ringo's touring project." },
    { event: "George Harrison's 'Cloud Nine' album", year: 1987, description: "Comeback hit with 'Got My Mind Set on You'." },
    { event: "Traveling Wilburys formed", year: 1988, description: "George, Dylan, Orbison, Petty, Lynne supergroup." },
    { event: "Paul McCartney's 'Flowers in the Dirt'", year: 1989, description: "Collaboration with Elvis Costello." },
    { event: "John Lennon's 'Imagine' film released", year: 1988, description: "Documentary directed by Andrew Solt." },
    { event: "Paul McCartney's Liverpool Oratorio premieres", year: 1991, description: "First classical composition." },
    { event: "John Lennon's star on Hollywood Walk of Fame", year: 1988, description: "Posthumous honor." },
    { event: "The Beatles at the BBC album released", year: 1994, description: "Live BBC recordings compilation." },
    { event: "Rock Band: The Beatles game released", year: 2009, description: "Interactive music video game." },
    { event: "Peter Jackson starts 'Get Back' restoration", year: 2019, description: "Using AI to restore footage." },
    { event: "Stella McCartney launches fashion brand", year: 2001, description: "Paul's daughter becomes top designer." },
    { event: "Sean Lennon releases 'Into the Sun'", year: 1998, description: "John's younger son's debut album." },
    { event: "Julian Lennon releases 'Valotte'", year: 1984, description: "John's elder son's debut album." },
];
