const beatlesEvents = [
    { event: "John Lennon forms The Quarrymen", year: 1956, description: "John forms his first skiffle group." },
    { event: "Paul McCartney meets John Lennon", year: 1957, description: "Meeting at the Woolton Parish Church Garden Fete." },
    { event: "Paul joins The Quarrymen", year: 1957, description: "Paul officially joins John's group." },
    { event: "George Harrison joins The Quarrymen", year: 1958, description: "George joins at Paul's recommendation." },
    { event: "The Quarrymen record 'That'll Be the Day'", year: 1958, description: "Their first amateur recording." },
    { event: "John Lennon's mother Julia dies", year: 1958, description: "A tragic loss that influenced John's music." },
    { event: "The Beatles name is chosen", year: 1960, description: "Official transition to the 'Beatles' name." },
    { event: "First Hamburg residency begins", year: 1960, description: "Performing at the Indra Club." },
    { event: "George Harrison deported from Germany", year: 1960, description: "Deported for being underage." },
    { event: "First gig at The Cavern Club", year: 1961, description: "Start of their legendary residency." },
    { event: "Brian Epstein first sees The Beatles", year: 1961, description: "At The Cavern Club." },
    { event: "The Beatles sign with Brian Epstein", year: 1962, description: "Brian officially becomes their manager." },
    { event: "Recording contract with Parlophone", year: 1962, description: "Signed by George Martin." },
    { event: "Ringo Starr joins The Beatles", year: 1962, description: "Replacing Pete Best on drums." },
    { event: "Release of 'Love Me Do'", year: 1962, description: "Their debut single." },
    { event: "John Lennon marries Cynthia Powell", year: 1962, description: "Private ceremony in Liverpool." },
    { event: "Release of 'Please Please Me' single", year: 1963, description: "Their first #1 hit." },
    { event: "Release of 'Please Please Me' album", year: 1963, description: "Debut LP." },
    { event: "John's son Julian Lennon born", year: 1963, description: "John's first child." },
    { event: "Beatlemania begins (Palladium performance)", year: 1963, description: "Headline show on 'Sunday Night at the London Palladium'." },
    { event: "Release of 'With The Beatles'", year: 1963, description: "Their second album." },
    { event: "The Beatles arrive in USA", year: 1964, description: "Landed at JFK airport." },
    { event: "First Ed Sullivan Show appearance", year: 1964, description: "73 million people watched." },
    { event: "Release of 'A Hard Day's Night' film", year: 1964, description: "Directed by Richard Lester." },
    { event: "Meeting Bob Dylan", year: 1964, description: "Crucial meeting in New York." },
    { event: "Release of 'Beatles for Sale'", year: 1964, description: "UK release." },
    { event: "Ringo marries Maureen Cox", year: 1965, description: "Official wedding." },
    { event: "Shea Stadium concert", year: 1965, description: "Record-breaking crowd." },
    { event: "The Beatles meet Elvis Presley", year: 1965, description: "At Elvis's home in Bel Air." },
    { event: "Awarded MBEs", year: 1965, description: "Member of the Order of the British Empire." },
    { event: "Release of 'Rubber Soul'", year: 1965, description: "Studio evolution." },
    { event: "George Harrison marries Pattie Boyd", year: 1966, description: "Meeting on the set of AHDN." },
    { event: "John's 'More popular than Jesus' quote", year: 1966, description: "Controversial interview in the Evening Standard." },
    { event: "Release of 'Revolver'", year: 1966, description: "Groundbreaking studio work." },
    { event: "Final official concert at Candlestick Park", year: 1966, description: "End of their touring years." },
    { event: "John Lennon meets Yoko Ono", year: 1966, description: "At Indica Gallery." },
    { event: "Recording 'Strawberry Fields Forever'", year: 1966, description: "Start of Sgt. Pepper sessions." },
    { event: "Release of 'Sgt. Pepper's Lonely Hearts Club Band'", year: 1967, description: "Masterpiece release." },
    { event: "Death of Brian Epstein", year: 1967, description: "Manager dies at 32." },
    { event: "Magical Mystery Tour telecast", year: 1967, description: "Airing on Boxing Day." },
    { event: "Apple Corps is formed", year: 1968, description: "Business venture launch." },
    { event: "Beatles travel to India (Rishikesh)", year: 1968, description: "Studying with Maharishi." },
    { event: "Recording of the 'White Album' begins", year: 1968, description: "Tense sessions begin." },
    { event: "Ringo Starr 'leaves' the band briefly", year: 1968, description: "Walked out during White Album sessions." },
    { event: "Release of 'The Beatles' (White Album)", year: 1968, description: "Double album release." },
    { event: "Rooftop Concert", year: 1969, description: "Final public performance." },
    { event: "John Lennon marries Yoko Ono", year: 1969, description: "Wedding in Gibraltar." },
    { event: "Paul McCartney marries Linda Eastman", year: 1969, description: "Wedding at Marylebone Registry Office." },
    { event: "Release of 'Abbey Road'", year: 1969, description: "Last recorded album." },
    { event: "John Lennon quietly leaves the band", year: 1969, description: "Informs group he wants 'divorce'." },
    { event: "Paul announces official breakup", year: 1970, description: "Public statement." },
    { event: "Release of 'Let It Be' album", year: 1970, description: "Final studio release." },
    { event: "Let It Be film premieres", year: 1970, description: "Documentary release." },
    { event: "George releases 'All Things Must Pass'", year: 1970, description: "Critically acclaimed solo debut." },
    { event: "Concert for Bangladesh", year: 1971, description: "Organized by George Harrison." },
    { event: "John Lennon releases 'Imagine'", year: 1971, description: "Legendary solo album." },
    { event: "Wings is formed by Paul McCartney", year: 1971, description: "Paul's new band." },
    { event: "The Beatles officially legally dissolve", year: 1975, description: "End of the legal entity." },
    { event: "Death of John Lennon", year: 1980, description: "Assassinated in New York." },
    { event: "The Beatles inducted into Rock Hall of Fame", year: 1988, description: "Posthumous honor for the group." },
    { event: "George Martin's death", year: 2016, description: "Fifth Beatle passes away." },
    { event: "Meeting with Elvis Presley", year: 1965, description: "Legendary summit." },
    { event: "Release of 'Yellow Submarine' film", year: 1968, description: "Animated classic." },
    { event: "John Lennon launches Plastic Ono Band", year: 1969, description: "New artistic direction." },
    { event: "The Beatles' 1 hits chart #1 worldwide", year: 2000, description: "Release of the best-selling compilation." },
    { event: "Anthology documentary series premieres", year: 1995, description: "Comprehensive history project." },
    { event: "George Harrison dies", year: 2001, description: "Passes away in Los Angeles." },
    { event: "Ringo Starr receives Knighthood", year: 2018, description: "Sir Richard Starkey." },
    { event: "Paul McCartney receives Knighthood", year: 1997, description: "Sir James Paul McCartney." },
    { event: "The Beatles' first recording at Abbey Road", year: 1962, description: "June 6, 1962." },
    { event: "The Beatles' first appearance on UK TV", year: 1962, description: "On 'People and Places'." },
    { event: "John Lennon's debut single 'Give Peace a Chance'", year: 1969, description: "Peace anthem." },
    { event: "Paul McCartney's debut solo album 'McCartney'", year: 1970, description: "Lo-fi masterpiece." },
    { event: "Release of 'Something' single", year: 1969, description: "George's first A-side." },
    { event: "Release of 'Hey Jude'", year: 1968, description: "Biggest selling single." },
    { event: "The 'Paul is Dead' rumor begins", year: 1969, description: "Urban legend peak." },
    { event: "The Beatles meet Maharishi", year: 1967, description: "Start of their spiritual era." },
    { event: "The Beatles' first Japan tour", year: 1966, description: "Performing at the Budokan." },
    { event: "The Beatles' first Manila tour controversy", year: 1966, description: "Escaping the Philippines." },
    { event: "Yoko Ono joins the studio sessions", year: 1968, description: "During White Album recording." },
    { event: "John Lennon's Lost Weekend begins", year: 1973, description: "Separation from Yoko." },
    { event: "Release of 'Double Fantasy'", year: 1980, description: "John's final album." },
    { event: "The Beatles' movie Help! premieres", year: 1965, description: "Royal premiere in London." },
    { event: "Release of single 'Ticket to Ride'", year: 1965, description: "Heavy metal precursor." },
    { event: "Release of 'A Day in the Life'", year: 1967, description: "Final track on Sgt. Pepper." },
    { event: "The Beatles play on 'Our World' broadcast", year: 1967, description: "Performing 'All You Need Is Love'." },
    { event: "John Lennon's MBE return", year: 1969, description: "Protesting Vietnam war." },
    { event: "Release of 'Strawberry Fields' / 'Penny Lane'", year: 1967, description: "Double A-side." },
    { event: "Stuart Sutcliffe dies", year: 1962, description: "Original bassist passes." },
    { event: "The Beatles' first concert at The Star-Club", year: 1962, description: "Hamburg residency." },
    { event: "Meeting with Muhammad Ali", year: 1964, description: "Photo op during Miami tour." },
    { event: "Release of 'Instant Karma!'", year: 1970, description: "John's hit single." },
    { event: "The Beatles play the Rooftop again (Anthology)", year: 1995, description: "Historical retrospection." },
    { event: "Beatles catalog arrives on iTunes", year: 2010, description: "Digital milestone." },
    { event: "The Beatles 'Now and Then' release", year: 2023, description: "Final song finished with AI." },
    { event: "Release of 'Get Back' documentary by Peter Jackson", year: 2021, description: "Rethinking the end." },
    { event: "Paul McCartney plays Giza pyramids", year: 2024, description: "Continuing the legacy." },
    { event: "Beatles first radio interview", year: 1962, description: "Radio Clatterbridge." },
    { event: "Ringo Starr joins Rory Storm and the Hurricanes", year: 1959, description: "Ringo's early band." },
    { event: "Meeting of The Beatles and The Beach Boys", year: 1966, description: "Mutual influence peak." }
];
